#!/bin/sh
set -e

# update interval in seconds
INTERVAL="1"

_usage() {
	echo "usage: $0 [network-interface]"
	echo "  eg: $0 eth0"
	echo "shows packets-per-second"
	exit 1
}
[ "$1" ] || _usage

_stat() {
	dev=$1
	stat=$2
	cat "/sys/class/net/$dev/statistics/$stat"
}

dev=$1
[ -d "/sys/class/net/$dev" ] || {
	echo "$dev not found"
	exit 1
}

while  true
do
	r1=$(_stat "$dev" "rx_packets")
	rd1=$(_stat "$dev" "rx_dropped")
	t1=$(_stat "$dev" "tx_packets")
	td1=$(_stat "$dev" "tx_dropped")

	sleep "$INTERVAL"

	r2=$(_stat "$dev" "rx_packets")
	rd2=$(_stat "$dev" "rx_dropped")
	t2=$(_stat "$dev" "tx_packets")
	td2=$(_stat "$dev" "tx_dropped")

	tx_pps=$((t2 - t1))
	tx_dropped_pps=$((td2 - td1))
	rx_pps=$((r2 - r1))
	rx_dropped_pps=$((rd2 - rd1))
	echo  "[$dev] tx: $tx_pps (dropped: $tx_dropped_pps) pkts/s / rx $dev : $rx_pps (dropped: $rx_dropped_pps) pkts/s"
done
